apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC5T+kl3fTCF+pcZGE+Ysne0xQDO+YsiKknTJiPO48Nacu7K6DanZXAzYmMdki//YlCXJ+mLQsTbT+o3KEHoGgChqTog8hp3qux9aJR+QsYqAdl3arAH9Yz+1Xm6ZEWPdIVsekD4S+j/pSR7ZlASre2CP4rFF4m0em5l5IJoOsu3fP2TBIU7VFkCUeUFumRYJNbBIaNXJ19yiYTkldy8TyzdLvF6Y05I7/LvY3068Po5QcEJ63/M3UUR8jyDtqncQshIqdAP9k4xsYfGVDq632Q3HtBuTAfdB+/9Hlp+Y/8iYBjmXy+bXDDm6z2M6KHkDrQCTCQ7RjaLT1IuoPjlBR/Ozz84gzoiykP5EYAhd3Y7WAuvQ1hXrk3GQKYxjbplBaYLfvSw7rA6MTR/W/UHQDXoihxhNQ6GFOLGuAq9NPmT64ZxMkqCRmWWHS7+ersq4KCzyY2Rjb7vH7SyQW4kWfb1NcAbQTLlJV3V8ardU9c/C1Rh5nMEGdSHbpd+GZQM/eJlxAXsxxjlIdMzAa4MEW9lRuqKqdzb1TJkAeUHl8bcYjj7TL/0iDfdaRMzaDW/G+WjhVm7aGeQo7XQEmXUSGQcTYJ0rNiMqaCEh9o0JPU/UoIRF8JiDjMJQwshUQHw4zaWxlNCTl5jX4FZA6f7yQgQE1ud9Cctep/QDBvviYfrxOvb0Yg9u/fayPrJqpkP6MOJ53UCdRTqIFOqCPacGZRTfm5rA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
