apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC9k1Lpq4aHvHaS6gU9toLG4Nlsnj/rIipCHEN8xAthKjXQhCCG/NPO4gVMzHkuQDV8mNZX+8nielzakBRp1kiHJWBfBQbXzoH/lYXp5ESYPL8usGhhU2B4QYBv2DaZ9hMfbUG7kxcvE6ik7z2UlVC+zYJLZ/gmbX7LtU8VnQkGU+sFsUHP21pafm/NwDK2UarIezNvckMMIITXIH0Lzim5qyKbf6z9khHl5ZOv1IhGGsUUfFPhYPPLd3vmYrgttvKmhNcfosdvS+Yi+q0UsEwcN77IUefB7g7fafj2DmXfsesyO5W6uVFZRJFeLh/4cEPXqsY/ATC0S37LtHf+E4KKxGK+Es8P7HDSOUwkcrwYiW/ImAUyAjphjHktc2wUMezHC3ZnZMO22JNilV35hb3nTcPaY7uAny5XTldqpnTQyALNCHUqYW2fyhrfHrMzsHoObv0kUWeggxmVQK3DQfuyZVfnQE7Ussz/RZRGbPOJvbIFN9NTNG4DDggh0crHJvSa/khAvf6RnhiLpbzrHJx0cQQ76O5ke91Krze83Te33+IJbXy5g+rP75owcJd1lDtg9k4zXy2SvRVBPOv5hOUaXWUrb+tC1wSK/NYfHE7XYZM4kG+h67+HhfpNOQW9QiYkDR/rlaVEKvMkV7fQA8o7TO55Ume/JT9PgHesVIsiyceErEkMA6bdG8oNjknloh8F2yBKqtE4ECc6KgGB6b1urxOIcA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
