apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/prod
    repoURL: https://github.com/chetan-rns/gitops-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
