apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/ishitasequeira/kam51040.git?ref=HEAD
  creationTimestamp: null
  name: cicd
spec: {}
status: {}
